from tkinter import *
from tkinter import messagebox
from PIL import Image, ImageTk
window = Tk()
window.title('My photo album')
window.geometry('400x420')
title = Label(window, text = 'My photo album', fg = 'white', bg = 'purple', width = 40)
title.pack(pady=10)
img_file = Image.open('strawberry.jpg')
img_file = img_file.resize((300, 180))
photo = ImageTk.PhotoImage(img_file)
pic = Label(window, image=photo)
pic.pack(pady=5)
def show_details():
    top = Toplevel()
    top.title('Photo details')
    top.geometry('200x120')
    info = Label(top, text = 'Taken on 1 June 2025')
    info.pack(pady=10)
    place = Label(top, text = 'Location : My garden')
    place.pack()
    top.mainloop()
details_btn = Button(window, text = 'see details', fg='white', bg = 'green', command = show_details)
details_btn.pack(pady=5)
window.mainloop()