file = open("bucket-list.txt", "w")
file.write("1. visit the eiffel towwer\n")
file.write("2. learn to play guitar\n")
file.write("3. learn to code my own game\n")
file.close()
print("bucket list saved to bucket-list.txt!")
file = open("bucket-list.txt", "r")
lines = file.readlines()
print(f"you have {len(lines)} in your bucket list.")
file.close()
file = open("bucket-list.txt", "a")
file.write("4/ Visit japan\n")
file.write("5. Run a 5k marathon\n")
file.close()
print("\n2 more items added!")
file = open("bucket-list.txt", "r")
print("\n ===Updated bucket list===")
print(file.read())
file.close()