file_name = "shopping_list.txt"
shopping_file = open(file_name, "w")
shopping_file.write("shopping_list\n")
shopping_file.write("Apples\n")
shopping_file.write("bread\n")
shopping_file.write("milk\n")
shopping_file.write("butter\n")
shopping_file.close()
print("shopping file succesfully created!")
shopping_file = open(file_name, "r")
print("\n=====Full shopping list=====")
content = shopping_file.read()
print(content)
shopping_file.close()
shopping_file = open(file_name, "a")
shopping_file.write("spaghetti\n")
shopping_file.write("juice\n")
shopping_file.write("water container\n")
shopping_file.close()
print("items successfully added!")
shopping_file = open(file_name, "r")
print("\n=====Updated shopping list=====")
updated_content = shopping_file.read()
print(updated_content)
shopping_file.close()
shopping_file = open(file_name,"r")
print("\n=====read shopping list line by line=====")
line_number = 1
for line in shopping_file:
    print("Line", line_number, ":", line.strip())
    line_number = line_number + 1
shopping_file.close()
print("\n================================")
print("shopping list manager summary")
print("================================")
print("file created:", file_name)
print("items were written, appended and read successfully!")
print("================================")