pasta = ("pasta arrabiata", "Italian", 20, "median")
biryani = ("chicken biryani", "indian", 45, "Hard")
print("Recipe 1:", pasta)
print("name:", pasta[0])
print("cuisine:", pasta[1])
print("difficulty:", pasta[-1])
all_recipes = (pasta, biryani)
print("\nFirst recipe name:", all_recipes[0][0])
print("second recipe name:", all_recipes[1][2], "mins")
print("pasta details (sliced):", all_recipes[1:3])
print("\nPasta recipe details:")
for detail in pasta:
    print("-", detail)
pasta_ingredients = {"tomato", "garlic", "olive oil", "chilli", "pasta", "garlic"}
biryani_ingredients = {"rice", "chicken", "onion", "garlic", "tomato", "spices"}
print("\nPasta ingredients:", pasta_ingredients)
print("\nbiryani ingredients:", biryani_ingredients)
print("total pasta ingredients:", len(pasta_ingredients))
pasta_ingredients.add("parmesan")
pasta_ingredients.discard("chilli")
print("\nUpdated pasta ingredients:", pasta_ingredients)
all_ingredients = pasta_ingredients.union(biryani_ingredients)
common = pasta_ingredients.intersection(biryani_ingredients)
only_pasta = pasta_ingredients.difference(biryani_ingredients)
unique_to_each = pasta_ingredients.symmetric_difference(biryani_ingredients)
print("\nAll ingredients (union):", all_ingredients)
print("common ingredients (intersection):", common)
print("only pasta (difference):", only_pasta)
print("Not shared (sym. difference):", unique_to_each)